<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    public function run()
    {
        // Create permissions
        $permissions = [
            'manage_users', // Permission to create, update, delete, and view users in the system.
            'manage_roles', // Permission to create, update, delete, and assign roles to users.
            'manage_permissions', // Permission to create, update, delete, and assign permissions to roles.
            'view_reports', // Permission to access and view various reports generated by the application.
            'manage_settings', // Permission to modify application settings and configurations.
            'edit_content', // Permission to edit existing content (e.g., posts, articles).
            'delete_content', // Permission to delete content from the system.
            'publish_content', // Permission to publish content, making it visible to the public.
            'view_content', // Permission to view all content available in the application.
            'view_own_profile', // Permission for users to view their own profile information.
            'edit_own_profile', // Permission for users to edit their own profile details.
            'create_content', // Permission to create new content (e.g., posts, comments).
            'comment', // Permission to leave comments on content.
            'like_content', // Permission to like or interact with content.
        ];

        foreach ($permissions as $permission) {
            Permission::create(['name' => $permission]);
        }

        // Create roles and assign permissions
        $admin = Role::create(['name' => 'Admin']);
        $admin->givePermissionTo($permissions); // Assign all permissions to Admin

        $editor = Role::create(['name' => 'Editor']);
        $editor->givePermissionTo(['edit_content', 'delete_content', 'publish_content', 'view_content']);

        $user = Role::create(['name' => 'User']);
        $user->givePermissionTo(['view_own_profile', 'edit_own_profile', 'create_content', 'comment']);

        $viewer = Role::create(['name' => 'Viewer']);
        $viewer->givePermissionTo(['view_content', 'like_content']);
    }
}